services:
  osb-remote:
    image: custom-osb
    container_name: osb
    build:
      context: osb
      dockerfile: Dockerfile.customosb
    volumes:
      - share-data:/share-data
    networks:
      - test-net
    environment:
      - "OSB_PROCEDURE=${OSB_PROCEDURE}"
      - "OSB_PARAMS=${OSB_PARAMS}"
      - "RUN_ID=${RUN_ID}"
      - "ENDPOINT=${ENDPOINT}"
      - "OSB_WORKLOADS_REPO=${OSB_WORKLOADS_REPO}"
    deploy:
      resources:
        limits:
          cpus: "${OSB_CPU_COUNT}"
          memory: ${OSB_MEM_SIZE}
volumes:
  share-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SHARE_DATA_PATH}
networks:
  test-net: